### ISSUE TITLE
[How-To] controller by operation name

### ISSUE THREAD

**Issue by patb23** [smartrecruiters/openapi-first#12]
Trying to use a controller that has 1+ operations, need help/suggestion on how to configure. The by-property controller only considers x-swagger-router-controller and don't know how to make use of operationid.

**Comment by kiebzak** [comment]
Hi @patb23!

The `by-property` operation middleware is dedicated to serve express middleware which are exported in separate files. If you want to configure it using `operationId` property, then you would just probably use something like this ('x-swagger-router-controller' is just a default property name and can be easily overridden):
```javascript
api.use(require('@smartrecruiters/openapi-first/middlewares/controllers/by-property')({
  dir: __dirname, 
  propertyName: 'operationId'
}))
```  
However, if I understood correctly I suppose you have a module that exports a couple of express middleware under some keys that will correspond to `operationId` property of your oas3 operation, like:
```javascript
module.exports.getAll = (req, res, next) => ...
module.exports.getOne = (req, res, next) => ...
module.exports.create = (req, res, next) => ...
module.exports.delete = (req, res, next) => ...
```

In this case, I would suggest using your custom operation middleware, which will look probably like this:
```javascript
module.exports = ({controller}) => operation => controller[operation.operationId]
```
And let's say above module is under `singleControllerMiddleware` variable and controller that export multiple express middleware is under `controller` variable, it will be used like:
```javascript
api.use(singleControllerMiddleware(controller))
```
and it is so simple that may be just inlined:
```javascript
api.use(operation => controller[operation.operationId])
```

Please tell me whether I get it right and this helps. If yes, if you need it I can add this `singleControllerMiddleware` to this library so you can just use it, or you are more than welcome to propose your middleware in a pull request.

Thank

**Comment by patb23** [comment]
Thank you for the explanation. Yes you got my question right and the _singleControllerMiddleware_ is what I need to implement. Thanks

**Comment by patb23** [comment]
> And let's say above module is under singleControllerMiddleware variable and controller that export multiple express middleware is under controller variable, it will be used like:

Sorry one clarification - The controller will still be referred by 'x-swagger-router-controller'?  So it will be a combination of controller  and operation id (when present) in spec.json that will be invoked. Correct?

**Comment by patb23** [comment]
Sorry to spam - I  - I tweaked the _by-property_ to meet my need
`   const  controller = require(path.join(dir, relativePath));       
 return controller[operation['operationId']];
`
